on:
  push:
    branches:
    - main

jobs:
  build:
    uses: cloud-cli/workflows/.github/workflows/docker-ghcr-build.yml@main
    with:
      name: cloud-cli/json-store
      baseImage: cloud-cli/node:latest
      defaultBranch: main
      type: node
      withSha: false
      withTag: true
